spring:
  datasource:
    password: kun123456789+
    url: jdbc:mysql://localhost:3306/basedb
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
